# This is a basic workflow to help you get started with Actions

name: enable_crazy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
  - cron: "0 16 * * WED"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  crazy_thu_enable:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "<!--KFC-->"
          replace: "#[CLICK HERE](https://m4tsuri.io/hidden/kfc_crazy_thu/index.html)"
          regex: false
